"""empty message

Revision ID: 464e37544470
Revises: 
Create Date: 2023-08-01 19:30:33.195090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464e37544470'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('theatre_id', sa.INTEGER(), nullable=True),
    sa.Column('show_id', sa.INTEGER(), nullable=True),
    sa.Column('ticket_price', sa.FLOAT(), nullable=False),
    sa.Column('show_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
