"""Updated theatre

Revision ID: 7821863fa3db
Revises: 
Create Date: 2023-07-23 16:35:25.868902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7821863fa3db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=200), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
